services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/kiruizz/NetBill-system.git
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:zzmOO0aoQWezLDa9Idf78tW0pOM2tyk2rtBtU65wlQ0=
      - key: DB_CONNECTION
        value: mysql
      - key: APP_NAME
        value: "Network Billing System"
      - key: APP_ENV
        value: local
      - key: APP_KEY
        value: base64:nnEn6K1HR2JH7ww+7yIc9j2ea2P37cnm3dbaGCvKmu8=
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: http://localhost:8000
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: billing_system
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ""

      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DRIVER
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: MEMCACHED_HOST
        value: 127.0.0.1
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: 6379

      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailhog
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: null
      - key: MAIL_FROM_NAME
        value: "${APP_NAME}"
      - key: MAIL_REPLY_TO_ADDRESS
        value: null
      - key: AWS_ACCESS_KEY_ID
        value: n
      - key: AWS_SECRET_ACCESS_KEY
        value: null
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_BUCKET
        value: null
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: false

      - key: PUSHER_APP_ID
        value: null
      - key: PUSHER_APP_KEY
        value: null
      - key: PUSHER_APP_SECRET
        value: null
      - key: PUSHER_APP_CLUSTER
        value: mt1

      - key: VITE_PUSHER_APP_KEY
        value: null     
      - key: VITE_PUSHER_APP_CLUSTER
        value: mt1